[package]
name = "fish_n_chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggegui = "0.3.8"
ggez = "0.9.3"
rand = "0.8.5"
rfd = "0.12.1"
